@file:Suppress("Unused")

package com.apsl.glideapp.core.ui.theme

import androidx.compose.ui.graphics.Color

object Colors {
    val LightPrimary = Color(0xFF0361A3)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightPrimaryContainer = Color(0xFFD1E4FF)
    val LightOnPrimaryContainer = Color(0xFF001D36)
    val LightSecondary = Color(0xFF535F70)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightSecondaryContainer = Color(0xFFD7E3F8)
    val LightOnSecondaryContainer = Color(0xFF101C2B)
    val LightTertiary = Color(0xFF406918)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightTertiaryContainer = Color(0xFFBFF190)
    val LightOnTertiaryContainer = Color(0xFF0D2000)
    val LightError = Color(0xFFBA1A1A)
    val LightErrorContainer = Color(0xFFFFDAD6)
    val LightOnError = Color(0xFFFFFFFF)
    val LightOnErrorContainer = Color(0xFF410002)
    val LightBackground = Color(0xFFFDFCFF)
    val LightOnBackground = Color(0xFF1A1C1E)
    val LightSurface = Color(0xFFFDFCFF)
    val LightOnSurface = Color(0xFF1A1C1E)
    val LightSurfaceVariant = Color(0xFFDFE2EB)
    val LightOnSurfaceVariant = Color(0xFF43474E)
    val LightOutline = Color(0xFF73777F)
    val LightInverseOnSurface = Color(0xFFF1F0F4)
    val LightInverseSurface = Color(0xFF2F3033)
    val LightInversePrimary = Color(0xFF9ECAFF)
    val LightShadow = Color(0xFF000000)
    val LightSurfaceTint = Color(0xFF0361A3)
    val LightOutlineVariant = Color(0xFFC3C6CF)
    val LightScrim = Color(0xFF000000)

    val DarkPrimary = Color(0xFF9ECAFF)
    val DarkOnPrimary = Color(0xFF003258)
    val DarkPrimaryContainer = Color(0xFF00497D)
    val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
    val DarkSecondary = Color(0xFFBBC7DB)
    val DarkOnSecondary = Color(0xFF253140)
    val DarkSecondaryContainer = Color(0xFF3B4858)
    val DarkOnSecondaryContainer = Color(0xFFD7E3F8)
    val DarkTertiary = Color(0xFFA4D577)
    val DarkOnTertiary = Color(0xFF1B3700)
    val DarkTertiaryContainer = Color(0xFF295000)
    val DarkOnTertiaryContainer = Color(0xFFBFF190)
    val DarkError = Color(0xFFFFB4AB)
    val DarkErrorContainer = Color(0xFF93000A)
    val DarkOnError = Color(0xFF690005)
    val DarkOnErrorContainer = Color(0xFFFFDAD6)
    val DarkBackground = Color(0xFF1A1C1E)
    val DarkOnBackground = Color(0xFFE2E2E6)
    val DarkSurface = Color(0xFF1A1C1E)
    val DarkOnSurface = Color(0xFFE2E2E6)
    val DarkSurfaceVariant = Color(0xFF43474E)
    val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
    val DarkOutline = Color(0xFF8D9199)
    val DarkInverseOnSurface = Color(0xFF1A1C1E)
    val DarkInverseSurface = Color(0xFFE2E2E6)
    val DarkInversePrimary = Color(0xFF0361A3)
    val DarkShadow = Color(0xFF000000)
    val DarkSurfaceTint = Color(0xFF9ECAFF)
    val DarkOutlineVariant = Color(0xFF43474E)
    val DarkScrim = Color(0xFF000000)

    private val Seed = Color(0xFF18293C)

    val NoParking = Color(0xFFC93C49)
    val NoRiding = Color(0xFF2F4496)
}
